### ISSUE TITLE
Problem with Setup -> Node resources

### ISSUE THREAD

**Issue by Portugalas** [TezosRio/taps#1]
Can't set up TAPS with my node.
When i set up : 
Base dir : /home/user
Tezos node alias : test
Full path to tezos client binary : /home/user/tezos
I get message : TAPS was unable to run transfer command below:
/home/user/tezos/tezos-client --base-dir **/home/user/.tezos-client** transfer 1 from test to tz_key --fee 0.05 --dry-run

Other setup:
Base dir : /home/user/tezos
Tezos node alias : test
Full path to tezos client binary : /home/user/tezos
message : TAPS was unable to run transfer command below:
/home/user/tezos/tezos-client --base-dir **/home/user/tezos/.tezos-client** transfer 1 from test to tz_key --fee 0.05 --dry-run

With second set up i get almost correct path, if not that dot. I removed that dot in setup.cfm file. But no success.
Maybe it because such command requires password for encrypted key ? 
Where i can find logs to find more detail error message?

**Comment by TezosRio** [comment]
Please, don't use this option, as it is deprecated. Instead, use Taps native wallet.
